### ISSUE TITLE
immuno.cwl error with star-fusion/star indices during staging input files on compute1

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/immuno-planning#10]

**Comment by susannasiebert** [comment]
@gschang please provide more details about the error at your convenience

**Comment by gschang** [comment]
The current immuno workflow (at https://github.com/genome/analysis-workflows/pull/1058) stops running on `compute1` with the following error. In sum, (1) This error happens with compute1. compute0 doesn't have such error. (2) The immuno workflow fails to stage input files for either `star_2.7.8a_index` or `star-fusion_1.10.1_index`. (3) This error results in rnaseq_star_fusion.cwl failure in the immuno workflow on compute1.

I listed two instances below. As you can see, both instances seem to fail during copying (or staging) genome index files. I tried them both at `/storage1/fs1/bga` and at `/scratch1/fs1/bga`, but they failed all. For information, these genome indices are recently updated at below.

`/gscmnt/gc2560/core/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star-fusion_1.10.1_index`
`/gscmnt/gc2560/core/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star_2.7.8a_index`


(1) immuno.cwl error with star-fusion_1.10.1_index
```
# error log at /storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno/immuno-165476-failed.log
......
[2022-03-20 11:00:37,17] [[38;5;1merror[0m] DispatchedConfigAsyncJobExecutionActor [[38;5;2m5df3894d[0mstar_fusion_detect:NA:1]: Error attempting to Execute
java.lang.Exception: Failed command instantiation
......
:
Could not localize /gscmnt/gc2560/core/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star-fusion_1.10.1_index -> /storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno/immuno.cwl/38d55112-a6b7-4187-a00d-cadccc765f23/call-rnaseq/rnaseq_star_fusion.cwl/5df3894d-b4e0-4629-b388-8a93d8121cfe/call-star_fusion_detect/inputs/-1878944677/star-fusion_1.10.1_index:
	/gscmnt/gc2560/core/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star-fusion_1.10.1_index doesn't exist
	/storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno/immuno.cwl/38d55112-a6b7-4187-a00d-cadccc765f23/call-rnaseq/rnaseq_star_fusion.cwl/5df3894d-b4e0-4629-b388-8a93d8121cfe/call-star_fusion_detect/inputs/-1878944677/star-fusion_1.10.1_index -> /gscmnt/gc2560/core/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star-fusion_1.10.1_index: Invalid cross-device link
	File not found /gscmnt/gc2560/core/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star-fusion_1.10.1_index/ref_genome.fa.gmap/.ref_genome.fa.gmap.sarray.LtYAY9
......

# I found that this directory caused the error:
$ ls /storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno/immuno.cwl/38d55112-a6b7-4187-a00d-cadccc765f23/call-rnaseq/rnaseq_star_fusion.cwl/5df3894d-b4e0-4629-b388-8a93d8121cfe/call-star_fusion_detect/inputs/-1878944677

drwx------. 4 gchang domain users 4.0K Mar 20 11:01 star-fusion_1.10.1_index.tmp/
```

(2) immuno.cwl error with star-fusion_1.10.1_index

```
# error message (The log file was removed)
Caused by: common.exception.AggregatedMessageException: Error(s):
:
Could not localize /gscmnt/gc2560/core/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star_2.7.8a_index -> /storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno/immuno.cwl/6a3d198d-400a-4354-ab9c-62bbb65280bb/call-rnaseq/rnaseq_star_fusion.cwl/9a84f960-10fe-44e5-93a1-ccfea4efbce6/call-star_align_fusion/inputs/-1878944677/star_2.7.8a_index:
	/gscmnt/gc2560/core/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star_2.7.8a_index doesn't exist
	/storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno/immuno.cwl/6a3d198d-400a-4354-ab9c-62bbb65280bb/call-rnaseq/rnaseq_star_fusion.cwl/9a84f960-10fe-44e5-93a1-ccfea4efbce6/call-star_align_fusion/inputs/-1878944677/star_2.7.8a_index -> /gscmnt/gc2560/core/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star_2.7.8a_index: Invalid cross-device link
	File not found /gscmnt/gc2560/core/GRC-human-build38_human_95_38_U2AF1_fix/rna_seq_annotation/star_2.7.8a_index/.SA.xgYgPK
	at common.validation.Validation$ValidationTry$.toTry$extension1(Validation.scala:89)

# I found that this directory caused the error:
$ ls /storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno/immuno.cwl-2nd/6a3d198d-400a-4354-ab9c-62bbb65280bb-failed/call-rnaseq/rnaseq_star_fusion.cwl/9a84f960-10fe-44e5-93a1-ccfea4efbce6/call-star_align_fusion/inputs/-1878944677 -l
total 1.1G
-rw-------. 1 gchang domain users 1.1G Mar 17 17:23 Homo_sapiens.GRCh38.95.gtf
 drwx------. 2 gchang domain users 4.0K Mar 17 17:24 star_2.7.8a_index.tmp
```

As you can see below, the second instance actually had succeeded in the `star_align_fusion` step withtout such input staging error. These errors look random, and the error with star-fusion_1.10.1_index happens more frequently. I launched immuno.cwl, but all of them failed.

Succeeded "star_align_fusion" step of the second instance:
`/storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno/immuno.cwl/38d55112-a6b7-4187-a00d-cadccc765f23/call-rnaseq/rnaseq_star_fusion.cwl/5df3894d-b4e0-4629-b388-8a93d8121cfe/call-star_align_fusion/execution`.

**Comment by gschang** [comment]
Discussing with John, the following is the succeeded immuno.cwl instance I made with the same immuno workflow repo on `compute0`.

(1) cromwell config, input YAML, and all intermediate files
- `/gscmnt/gc2764/cad/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno`
- `/gscmnt/gc2764/cad/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno/immuno.cwl/fc28f092-2bc3-45d3-8da9-57f443729eb9`

(2) LSF job log file
`/gscmnt/gc2764/cad/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/6.immuno/immuno-120h-4041486.log`

(3) final results of immuno.cwl
`/gscmnt/gc2764/cad/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/8.results`

**Comment by gschang** [comment]
For more information, this error happens only in immuno.cwl so far, which scratches my head. In fact, the `rnaseq_star_fusion.cwl` workflow succeeded without any error on compute1 (with the same HCC1395 dataset) when I ran it separately (not as a part of immuno.cwl).

The following is the instance of my succeeded `rnaseq_star_fusion.cwl` workflow as an example.

`/storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/2.rnaseq_star_fusion`
(job log: /storage1/fs1/bga/Active/gchang/work/14_BGA-WALKER-2/220301-immuno4cwl-star-fusion/2.rnaseq_star_fusion/rnaseq_star_fusion-189112.log)

In sum, this error happens in the `rnaseq_star_fusion.cwl` subworkflow, when I run the immuno.cwl workflow.

**Comment by johnegarza** [comment]
This issue was determined to be due to an environment misconfiguration that led to the input files not being mounted at the expected location in the main Cromwell process (but not the per-step subprocesses). However, this brought to light the fact that several of these large inputs were being unnecessarily copied by Cromwell while attempting to stage the files, due to their types being specified as `Directory`. Recall that the reference fasta input is already [a compound `File`/`string` type](https://github.com/genome/analysis-workflows/blob/2f65fc96207a71b1cda4e246f808bed056608cd0/definitions/pipelines/immuno.cwl#L105) to allow specifying it as a string on the MGI compute cluster- this prevents Cromwell from copying it and instead points to the single canonical copy in the GMS core location. It also allows use of the legacy storage0 `/gscmnt` path on storage1 in order to maintain backwards compatibility (as long as Cromwell is configured to always mount the storage1 path accordingly in the subprocess for each pipeline step, since the main process will not validate the path). Updating these inputs to compound `Directory`/`string` types and specifying them as `string`s solved the issue without requiring a fix for the environment misconfiguration, and saved the storage and time needed to copy them each time the pipeline was run. Included in https://github.com/genome/analysis-workflows/pull/1058
