### ISSUE TITLE
Add missing species argument to the immuno workflow

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/immuno-planning#9]
This argument is already exposed in pvacseq itself but not included in the relevant cwl files.

**Comment by johnegarza** [comment]
After further review and slack discussion, we realized this change is not needed. The pvactools pipelines determine the sample species from the HLA alleles that are passed in, so there is no need to add this option.

**Comment by gschang** [comment]
It makes sense to me now--this is why the species option is not exposed in pvactools command. I just learned that this automatic parameterization for the species argument from HLA typing input. I agree in that the immuno workflow doesn't need this species input for proteomic similarity search.
